services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    depends_on:
      discovery-server:
        condition: service_started
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - minimarket_mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  ms-auth:
    build: ./ms-auth
    depends_on:
      discovery-server:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_auth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8084:8084"

  ms-inventario:
    build: ./ms-inventario
    depends_on:
      discovery-server:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_inventario
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      MS_PRODUCTOS_URL: http://ms-producto:8081/api/productos
      MS_NOTIFICACIONES_URL: http://ms-notificaciones:8089/api/notificaciones
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8086:8086"

  ms-proveedores:
    build: ./ms-proveedores
    depends_on:
      discovery-server:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_proveedores
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      MS_PRODUCTOS_URL: http://ms-producto:8081/api/productos
      MS_INVENTARIO_URL: http://ms-inventario:8086/api/inventory/product
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8087:8087"

  ms-notificaciones:
    build: ./ms-notificaciones
    depends_on:
      discovery-server:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_notificaciones
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    ports:
      - "8089:8089"

volumes:
  minimarket_mysql:
