spring.application.name=ms-gateway
server.port=8080

# Eureka Client Discovery Configuration
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Spring Cloud Gateway WebMVC Routing Config
# Routes for ms-auth
spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth-login
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-auth
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-auth-roles
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-auth
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/roles/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-auth-users
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-auth
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/users/**

# Routes for ms-configuracion
spring.cloud.gateway.server.webmvc.routes[3].id=ms-configuracion-categories
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ms-configuracion
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/categories/**

spring.cloud.gateway.server.webmvc.routes[4].id=ms-configuracion-taxes
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ms-configuracion
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/taxes/**

# Routes for ms-producto
spring.cloud.gateway.server.webmvc.routes[5].id=ms-producto
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ms-producto
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/productos/**

# Routes for ms-cliente
spring.cloud.gateway.server.webmvc.routes[6].id=ms-cliente
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://ms-cliente
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/customers/**
